'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin

 '''<summary>
 '''lblAllowMultipleCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowMultipleCategories As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowMultipleCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowMultipleCategories As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblSummaryModel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummaryModel As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddSummaryModel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddSummaryModel As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblAllowAttachments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowAttachments As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowAttachments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowAttachments As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowWLW control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowWLW As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowWLW control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowWLW As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblVocabularyId control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblVocabularyId As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddVocabularyId control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddVocabularyId As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblWLWRecentPostsMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblWLWRecentPostsMax As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtWLWRecentPostsMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtWLWRecentPostsMax As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblModifyPageDetails control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblModifyPageDetails As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkModifyPageDetails control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkModifyPageDetails As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowAllLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowAllLocales As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowAllLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowAllLocales As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''cmdEditTagsML control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEditTagsML As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lblRssDefaultNrItems control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssDefaultNrItems As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssDefaultNrItems control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssDefaultNrItems As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssMaxNrItems control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssMaxNrItems As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssMaxNrItems control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssMaxNrItems As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssTtl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssTtl As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssTtl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssTtl As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEmail As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssDefaultCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssDefaultCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssDefaultCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssDefaultCopyright As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssAllowContentInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssAllowContentInFeed As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkRssAllowContentInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkRssAllowContentInFeed As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblRssImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssImageWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssImageWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssImageHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssImageHeight As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRssImageHeight control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRssImageHeight As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRssImageSizeAllowOverride control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRssImageSizeAllowOverride As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkRssImageSizeAllowOverride control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkRssImageSizeAllowOverride As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''cmdEditCategoriesML control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEditCategoriesML As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''treeState control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents treeState As Global.System.Web.UI.WebControls.HiddenField

 '''<summary>
 '''cmdCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdUpdate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
End Class
