'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BlogImport

 '''<summary>
 '''wizBlogImport control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents wizBlogImport As Global.System.Web.UI.WebControls.Wizard

 '''<summary>
 '''Step0 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Step0 As Global.System.Web.UI.WebControls.WizardStep

 '''<summary>
 '''lblTarget control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTarget As Global.System.Web.UI.UserControl

 '''<summary>
 '''lblTargetName control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTargetName As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cmdBrowse control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdBrowse As Global.System.Web.UI.HtmlControls.HtmlInputFile

 '''<summary>
 '''lblLoadMessage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblLoadMessage As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''Step1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Step1 As Global.System.Web.UI.WebControls.WizardStep

 '''<summary>
 '''txtAnalysis control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtAnalysis As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblImportCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImportCategories As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkImportCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkImportCategories As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblImportMissingCategoriesAsKeywords control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImportMissingCategoriesAsKeywords As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkImportMissingCategoriesAsKeywords control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkImportMissingCategoriesAsKeywords As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblImportComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImportComments As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkImportComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkImportComments As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''Step2 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Step2 As Global.System.Web.UI.WebControls.WizardStep

 '''<summary>
 '''txtReport control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtReport As Global.System.Web.UI.WebControls.TextBox
End Class
