'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BlogEdit

 '''<summary>
 '''lblTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTitle As Global.DotNetNuke.Modules.Blog.Controls.ShortTextEdit

 '''<summary>
 '''lblDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDescription As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtDescription As Global.DotNetNuke.Modules.Blog.Controls.LongTextEdit

 '''<summary>
 '''rowLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rowLocale As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''lblLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblLocale As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddLocale As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''rowFullLocalization control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rowFullLocalization As Global.System.Web.UI.HtmlControls.HtmlGenericControl

 '''<summary>
 '''lblFullLocalization control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblFullLocalization As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkFullLocalization control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkFullLocalization As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImage As Global.System.Web.UI.UserControl

 '''<summary>
 '''imgBlogImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents imgBlogImage As Global.System.Web.UI.WebControls.Image

 '''<summary>
 '''fileImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents fileImage As Global.System.Web.UI.WebControls.FileUpload

 '''<summary>
 '''cmdImageRemove control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdImageRemove As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''lblPublic control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPublic As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkPublic control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkPublic As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblSyndicate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSyndicate As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkSyndicate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkSyndicate As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblSyndicationEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSyndicationEmail As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtSyndicationEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtSyndicationEmail As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtCopyright As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblIncludeImagesInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblIncludeImagesInFeed As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkIncludeImagesInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkIncludeImagesInFeed As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblIncludeAuthorInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblIncludeAuthorInFeed As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkIncludeAuthorInFeed control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkIncludeAuthorInFeed As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblMustApproveGhostPosts control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMustApproveGhostPosts As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkMustApproveGhostPosts control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkMustApproveGhostPosts As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblPublishAsOwner control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPublishAsOwner As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkPublishAsOwner control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkPublishAsOwner As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblPermissions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPermissions As Global.System.Web.UI.UserControl

 '''<summary>
 '''ctlPermissions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlPermissions As Global.DotNetNuke.Modules.Blog.Security.Controls.BlogPermissionsGrid

 '''<summary>
 '''cmdUpdate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''hlCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hlCancel As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
End Class
