'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Blog

 '''<summary>
 '''cmdManageBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdManageBlogs As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdEditPost control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdEditPost As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdBlog As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''vtContents control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents vtContents As Global.DotNetNuke.Modules.Blog.Templating.ViewTemplate

 '''<summary>
 '''ctlComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ctlComments As Global.DotNetNuke.Modules.Blog.Controls.Comments
End Class
