'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditEntry

 '''<summary>
 '''lblTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''valTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''lblPublishDate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPublishDate As Global.System.Web.UI.UserControl

 '''<summary>
 '''dpEntryDate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dpEntryDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

 '''<summary>
 '''tpEntryTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tpEntryTime As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker

 '''<summary>
 '''litTimezone control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents litTimezone As Global.System.Web.UI.WebControls.Literal

 '''<summary>
 '''lblSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtDescriptionText control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtDescriptionText As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''valDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''lblDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDescription As Global.System.Web.UI.UserControl

 '''<summary>
 '''pnlCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlCategories As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCategories As Global.System.Web.UI.UserControl

 '''<summary>
 '''dtCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dtCategories As Global.DotNetNuke.Web.UI.WebControls.DnnTreeView

 '''<summary>
 '''lblTags control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTags As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTags control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTags As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''pnlUploads control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlUploads As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblAddPicture control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAddPicture As Global.System.Web.UI.UserControl

 '''<summary>
 '''picFilename control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents picFilename As Global.System.Web.UI.HtmlControls.HtmlInputFile

 '''<summary>
 '''btnUploadPicture control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnUploadPicture As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''lblAltText control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAltText As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtAltText control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtAltText As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblAddAttachment control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAddAttachment As Global.System.Web.UI.UserControl

 '''<summary>
 '''attFilename control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents attFilename As Global.System.Web.UI.HtmlControls.HtmlInputFile

 '''<summary>
 '''btnUploadAttachment control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnUploadAttachment As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''lblAttachmentDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAttachmentDescription As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtAttachmentDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtAttachmentDescription As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''dgLinkedFiles control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dgLinkedFiles As Global.System.Web.UI.WebControls.DataGrid

 '''<summary>
 '''pnlComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlComments As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblAllowComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowComments As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowComments As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblDisplayCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDisplayCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkDisplayCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkDisplayCopyright As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''pnlCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlCopyright As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtCopyright As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''cmdPublish control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdPublish As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdDraft control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDraft As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''hlCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hlCancel As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''valSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

 '''<summary>
 '''valEntry control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valEntry As Global.System.Web.UI.WebControls.CustomValidator

 '''<summary>
 '''valUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valUpload As Global.System.Web.UI.WebControls.CustomValidator
End Class
