'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EntryEdit

 '''<summary>
 '''lblBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblBlog As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddBlog As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''valTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''lblSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtDescriptionText control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtDescriptionText As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblSummaryPrecedingWarning control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummaryPrecedingWarning As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''pnlPublished control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlPublished As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblPublished control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPublished As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkPublished control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkPublished As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''pnlComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlComments As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblAllowComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowComments As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowComments As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblDisplayCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDisplayCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkDisplayCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkDisplayCopyright As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''pnlCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlCopyright As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCopyright As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtCopyright control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtCopyright As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblPublishDate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPublishDate As Global.System.Web.UI.UserControl

 '''<summary>
 '''dpEntryDate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dpEntryDate As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

 '''<summary>
 '''tpEntryTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tpEntryTime As Global.DotNetNuke.Web.UI.WebControls.DnnTimePicker

 '''<summary>
 '''litTimezone control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents litTimezone As Global.System.Web.UI.WebControls.Literal

 '''<summary>
 '''lblLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblLocale As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddLocale control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddLocale As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblImage As Global.System.Web.UI.UserControl

 '''<summary>
 '''imgEntryImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents imgEntryImage As Global.System.Web.UI.WebControls.Image

 '''<summary>
 '''fileImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents fileImage As Global.System.Web.UI.WebControls.FileUpload

 '''<summary>
 '''cmdImageRemove control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdImageRemove As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''pnlCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlCategories As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCategories As Global.System.Web.UI.UserControl

 '''<summary>
 '''dtCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents dtCategories As Global.DotNetNuke.Web.UI.WebControls.DnnTreeView

 '''<summary>
 '''lblTags control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTags As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtTags control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTags As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''cmdSave control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdSave As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''hlCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents hlCancel As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''valSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

 '''<summary>
 '''valEntry control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valEntry As Global.System.Web.UI.WebControls.CustomValidator

 '''<summary>
 '''valUpload control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valUpload As Global.System.Web.UI.WebControls.CustomValidator
End Class
