'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Settings

 '''<summary>
 '''lblTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTemplate As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddTemplate As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblAllowMultipleCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowMultipleCategories As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowMultipleCategories control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowMultipleCategories As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowHtmlSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowHtmlSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowHtmlSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowHtmlSummary As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowAttachments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowAttachments As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowAttachments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowAttachments As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowWLW control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowWLW As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowWLW control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowWLW As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowAllLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowAllLocales As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowAllLocales control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowAllLocales As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEmail As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblVocabularyId control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblVocabularyId As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddVocabularyId control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddVocabularyId As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblWLWRecentEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblWLWRecentEntriesMax As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtWLWRecentEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtWLWRecentEntriesMax As Global.System.Web.UI.WebControls.TextBox
End Class
