'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewTagsSettings

 '''<summary>
 '''lblDisplayMode control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDisplayMode As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddlDisplayMode control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddlDisplayMode As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblTelerikSkin control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTelerikSkin As Global.System.Web.UI.UserControl

 '''<summary>
 '''ddlTelerikSkin control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents ddlTelerikSkin As Global.System.Web.UI.WebControls.DropDownList
End Class
