'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ArchiveSettings

    '''<summary>
    '''lblDisplayMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayMode As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlDisplayMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisplayMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblListMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListMode As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''ddlListMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlListMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblLoadCss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoadCss As Global.DotNetNuke.UI.UserControls.LabelControl

    '''<summary>
    '''rblLoadCss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblLoadCss As Global.System.Web.UI.WebControls.RadioButtonList
End Class
