'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditBlog

    '''<summary>
    '''lblTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescription As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valTitleDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valTitleDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblPublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPublic As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkPublic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPublic As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUserIdentity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserIdentity As Global.System.Web.UI.UserControl

    '''<summary>
    '''rdoUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoUserName As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblAuthorMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuthorMode As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlAuthorMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAuthorMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMetaWebBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMetaWebBlog As Global.System.Web.UI.UserControl

    '''<summary>
    '''lblMetaWeblogNotAvailable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMetaWeblogNotAvailable As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMetaWeblogUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMetaWeblogUrl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUsersComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsersComments As Global.System.Web.UI.UserControl

    '''<summary>
    '''rdoUsersComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoUsersComments As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblAnonymousComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnonymousComments As Global.System.Web.UI.UserControl

    '''<summary>
    '''rdoAnonymousComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoAnonymousComments As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblTrackbacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTrackbacks As Global.System.Web.UI.UserControl

    '''<summary>
    '''rdoTrackbacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoTrackbacks As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaptcha As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCaptcha As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAutoTrackbacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAutoTrackbacks As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAutoTrackbacks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAutoTrackbacks As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEmailNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailNotification As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEmailNotification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEmailNotification As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSyndicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSyndicate As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkSyndicate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSyndicate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSyndicateIndependant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSyndicateIndependant As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkSyndicateIndependant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSyndicateIndependant As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSyndicationEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSyndicationEmail As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtSyndicationEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSyndicationEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRegenerate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegenerate As Global.System.Web.UI.UserControl

    '''<summary>
    '''cmdGenerateLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerateLinks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dnnSitePanelChildBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dnnSitePanelChildBlogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''fsChildBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fsChildBlogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lstChildBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstChildBlogs As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''cmdAddChildBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddChildBlog As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdEditChildBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdEditChildBlog As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdDeleteChildBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteChildBlog As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCancel As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
End Class
