'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class EditBlog

 '''<summary>
 '''valSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

 '''<summary>
 '''valTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''valTitleDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents valTitleDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

 '''<summary>
 '''lblOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblOptions As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblOptionsDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblOptionsDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblTitleDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTitleDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblDescriptionDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDescriptionDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''chkPublic control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkPublic As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblUserIdentity control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblUserIdentity As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''rdoUserName control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rdoUserName As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''lblMetaWeblogOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMetaWeblogOptions As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblMetaWeblogOptionsDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMetaWeblogOptionsDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblMetaWeblogUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMetaWeblogUrl As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblTwitterIntegration control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTwitterIntegration As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''chkEnableTwitterIntegration control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkEnableTwitterIntegration As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblTwitterUsername control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTwitterUsername As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtTwitterUsername control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTwitterUsername As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblTwitterPassword control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTwitterPassword As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtTwitterPassword control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTwitterPassword As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblTweetTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTweetTemplate As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtTweetTemplate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtTweetTemplate As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblAvailableTokens control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAvailableTokens As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblCommentOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCommentOptions As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblCommentOptionsDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCommentOptionsDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblUsersComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblUsersComments As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''rdoUsersComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rdoUsersComments As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''lblAnonymousComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAnonymousComments As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''rdoAnonymousComments control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rdoAnonymousComments As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''lblTrackbacks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTrackbacks As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''rdoTrackbacks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rdoTrackbacks As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''chkEmailNotification control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkEmailNotification As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''chkCaptcha control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkCaptcha As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblTrackbackOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTrackbackOptions As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblTrackbackOptionsDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTrackbackOptionsDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''chkAutoTrackbacks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAutoTrackbacks As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblSyndicationOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSyndicationOptions As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''chkSyndicate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkSyndicate As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''chkSyndicateIndependant control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkSyndicateIndependant As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblSyndicationEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSyndicationEmail As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''txtSyndicationEmail control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtSyndicationEmail As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblDateTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDateTime As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblDateTimeDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDateTimeDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblTimeZone control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblTimeZone As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cboTimeZone control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cboTimeZone As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblCulture control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCulture As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cboCulture control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cboCulture As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblDateFormat control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblDateFormat As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cboDateFormat control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cboDateFormat As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblRegenerate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRegenerate As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblRegenerateDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRegenerateDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''cmdGenerateLinks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdGenerateLinks As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''pnlChildBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlChildBlogs As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblChildBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblChildBlogs As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblChildBlogsDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblChildBlogsDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lstChildBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lstChildBlogs As Global.System.Web.UI.WebControls.ListBox

 '''<summary>
 '''btnAddChildBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnAddChildBlog As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''btnEditChildBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnEditChildBlog As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''btnDeleteChildBlog control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents btnDeleteChildBlog As Global.System.Web.UI.WebControls.Button

 '''<summary>
 '''cmdUpdate control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdCancel control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdDelete control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
End Class
