'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ModuleOptions

 '''<summary>
 '''secGeneralSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents secGeneralSettings As Global.System.Web.UI.UserControl

 '''<summary>
 '''tblGeneralSetting control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tblGeneralSetting As Global.System.Web.UI.HtmlControls.HtmlTable

 '''<summary>
 '''lblMandatory control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMandatory As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkForceDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkForceDescription As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowSummaryHtml control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowSummaryHtml As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowSummaryHtml control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowSummaryHtml As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''trSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trSummary As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtSummaryLimit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtSummaryLimit As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''trSearchSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trSearchSummary As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblSearchSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblSearchSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtSearchLimit control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtSearchLimit As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''Tr1 control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents Tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblMaxImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblMaxImageWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtMaxImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtMaxImageWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRecentEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRecentEntriesMax As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRecentEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRecentEntriesMax As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblRecentRssEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRecentRssEntriesMax As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtRecentRssEntriesMax control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtRecentRssEntriesMax As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''secCommentSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents secCommentSettings As Global.System.Web.UI.UserControl

 '''<summary>
 '''tblCommentSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tblCommentSettings As Global.System.Web.UI.HtmlControls.HtmlTable

 '''<summary>
 '''lblShowGravatars control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowGravatars As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowGravatars control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowGravatars As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''trGravatarImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trGravatarImageWidth As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblGravatarImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblGravatarImageWidth As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtGravatarImageWidth control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtGravatarImageWidth As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''trGravatarRating control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trGravatarRating As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblGravatarRating control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblGravatarRating As Global.System.Web.UI.UserControl

 '''<summary>
 '''rblGravatarRating control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rblGravatarRating As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''trGravatarDefaultImageUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trGravatarDefaultImageUrl As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblGravatarDefaultImageUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblGravatarDefaultImageUrl As Global.System.Web.UI.UserControl

 '''<summary>
 '''rblDefaultImage control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents rblDefaultImage As Global.System.Web.UI.WebControls.RadioButtonList

 '''<summary>
 '''trGravatarDefaultImageCustomURL control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents trGravatarDefaultImageCustomURL As Global.System.Web.UI.HtmlControls.HtmlTableRow

 '''<summary>
 '''lblGravatarDefaultImageCustomURL control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblGravatarDefaultImageCustomURL As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtGravatarDefaultImageCustomURL control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtGravatarDefaultImageCustomURL As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''lblShowWebsite control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowWebsite As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowWebsite control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowWebsite As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblShowTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowCommentTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowCommentTitle As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowCommentAnchors control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowCommentAnchors As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowCommentAnchors control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowCommentAnchors As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowCommentImages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowCommentImages As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowCommentImages control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowCommentImages As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblAllowCommentFormatting control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAllowCommentFormatting As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkAllowCommentFormatting control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkAllowCommentFormatting As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''secSEOSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents secSEOSettings As Global.System.Web.UI.UserControl

 '''<summary>
 '''tblSEOSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tblSEOSettings As Global.System.Web.UI.HtmlControls.HtmlTable

 '''<summary>
 '''lblShowUniqueTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowUniqueTitle As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowUniqueTitle control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowUniqueTitle As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblShowSeoFriendlyUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowSeoFriendlyUrl As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowSeoFriendlyUrl control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowSeoFriendlyUrl As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblRegenerateLinks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblRegenerateLinks As Global.System.Web.UI.UserControl

 '''<summary>
 '''cmdGenerateLinks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdGenerateLinks As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''secRSSSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents secRSSSettings As Global.System.Web.UI.UserControl

 '''<summary>
 '''tblRSSSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tblRSSSettings As Global.System.Web.UI.HtmlControls.HtmlTable

 '''<summary>
 '''lblIncludeBody control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblIncludeBody As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkIncludeBody control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkIncludeBody As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblIncludeCategoriesInDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblIncludeCategoriesInDescription As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkIncludeCategoriesInDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkIncludeCategoriesInDescription As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblIncludeTagsInDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblIncludeTagsInDescription As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkIncludeTagsInDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkIncludeTagsInDescription As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblFeedCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblFeedCacheTime As Global.System.Web.UI.UserControl

 '''<summary>
 '''txtFeedCacheTime control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents txtFeedCacheTime As Global.System.Web.UI.WebControls.TextBox

 '''<summary>
 '''secAdvancedSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents secAdvancedSettings As Global.System.Web.UI.UserControl

 '''<summary>
 '''tblAdvancedSettings control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents tblAdvancedSettings As Global.System.Web.UI.HtmlControls.HtmlTable

 '''<summary>
 '''lblUploadOption control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblUploadOption As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkUploadOption control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkUploadOption As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblPageBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblPageBlogs As Global.System.Web.UI.UserControl

 '''<summary>
 '''cmbPageBlogs control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmbPageBlogs As Global.System.Web.UI.WebControls.DropDownList

 '''<summary>
 '''lblEnableDNNSearch control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEnableDNNSearch As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkEnableDNNSearch control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkEnableDNNSearch As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblEnableBookmarks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEnableBookmarks As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkEnableBookmarks control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkEnableBookmarks As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblEnforceSummaryTruncation control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblEnforceSummaryTruncation As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkEnforceSummaryTruncation control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkEnforceSummaryTruncation As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''lblShowSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblShowSummary As Global.System.Web.UI.UserControl

 '''<summary>
 '''chkShowSummary control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents chkShowSummary As Global.System.Web.UI.WebControls.CheckBox

 '''<summary>
 '''cmdUpdateOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdUpdateOptions As Global.System.Web.UI.WebControls.LinkButton

 '''<summary>
 '''cmdCancelOptions control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents cmdCancelOptions As Global.System.Web.UI.WebControls.LinkButton
End Class
