'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModuleOptions

    '''<summary>
    '''lblMandatory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMandatory As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkForceDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkForceDescription As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSummary As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtSummaryLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSummaryLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSearchSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSearchSummary As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtSearchLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchLimit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMaxImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxImageWidth As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtMaxImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxImageWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRecentEntriesMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecentEntriesMax As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtRecentEntriesMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecentEntriesMax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblShowGravatars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowGravatars As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkShowGravatars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowGravatars As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblGravatarImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGravatarImageWidth As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtGravatarImageWidth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravatarImageWidth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGravatarRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGravatarRating As Global.System.Web.UI.UserControl

    '''<summary>
    '''rblGravatarRating control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGravatarRating As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblGravatarDefaultImageUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGravatarDefaultImageUrl As Global.System.Web.UI.UserControl

    '''<summary>
    '''rblDefaultImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblDefaultImage As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''lblGravatarDefaultImageCustomURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGravatarDefaultImageCustomURL As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtGravatarDefaultImageCustomURL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravatarDefaultImageCustomURL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblShowWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowWebsite As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkShowWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowWebsite As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblShowTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowTitle As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkShowCommentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowCommentTitle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowCommentAnchors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowCommentAnchors As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowCommentAnchors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowCommentAnchors As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowCommentImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowCommentImages As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowCommentImages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowCommentImages As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowCommentFormatting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowCommentFormatting As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowCommentFormatting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowCommentFormatting As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblShowSeoFriendlyUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowSeoFriendlyUrl As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkShowSeoFriendlyUrl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowSeoFriendlyUrl As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRegenerateLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegenerateLinks As Global.System.Web.UI.UserControl

    '''<summary>
    '''cmdGenerateLinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdGenerateLinks As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblIncludeBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncludeBody As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkIncludeBody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeBody As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIncludeCategoriesInDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncludeCategoriesInDescription As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkIncludeCategoriesInDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeCategoriesInDescription As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblIncludeTagsInDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIncludeTagsInDescription As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkIncludeTagsInDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIncludeTagsInDescription As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblFeedCacheTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFeedCacheTime As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtFeedCacheTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeedCacheTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRecentRssEntriesMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRecentRssEntriesMax As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtRecentRssEntriesMax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecentRssEntriesMax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAllowWLW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowWLW As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowWLW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowWLW As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseWLWExcerpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseWLWExcerpt As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkUseWLWExcerpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseWLWExcerpt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCatVocabRoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCatVocabRoot As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlCatVocabRoot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCatVocabRoot As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAllowMultipleCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowMultipleCategories As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowMultipleCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowMultipleCategories As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUploadOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUploadOption As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkUploadOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUploadOption As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPageBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPageBlogs As Global.System.Web.UI.UserControl

    '''<summary>
    '''cmbPageBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPageBlogs As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSocialSharingMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSocialSharingMode As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlSocialSharingMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSocialSharingMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAddThisId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddThisId As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtAddThisId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddThisId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFacebookAppId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFacebookAppId As Global.System.Web.UI.UserControl

    '''<summary>
    '''FacebookAppId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FacebookAppId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEnablePlusOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnablePlusOne As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEnablePlusOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnablePlusOne As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEnableTwitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnableTwitter As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEnableTwitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnableTwitter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEnableLinkedIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnableLinkedIN As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEnableLinkedIN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnableLinkedIN As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEnforceSummaryTruncation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnforceSummaryTruncation As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEnforceSummaryTruncation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnforceSummaryTruncation As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblShowSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShowSummary As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkShowSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkShowSummary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowSummaryHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowSummaryHtml As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowSummaryHtml control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowSummaryHtml As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAllowChildBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllowChildBlogs As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkAllowChildBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllowChildBlogs As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEnableArchiveDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnableArchiveDropDown As Global.System.Web.UI.UserControl

    '''<summary>
    '''chkEnableArchiveDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnableArchiveDropDown As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMigrateChildblogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMigrateChildblogs As Global.System.Web.UI.UserControl

    '''<summary>
    '''lblChildBlogsStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChildBlogsStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmdMigrateChildblogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdMigrateChildblogs As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblHostFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHostFiles As Global.System.Web.UI.UserControl

    '''<summary>
    '''cblHostFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblHostFiles As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblPortalFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPortalFiles As Global.System.Web.UI.UserControl

    '''<summary>
    '''cblPortalFiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblPortalFiles As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''cmdUpdateOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUpdateOptions As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''hlCancelOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlCancelOptions As Global.System.Web.UI.WebControls.HyperLink
End Class
