'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ViewEntry

    '''<summary>
    '''lblTrackback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTrackback As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBlogTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBlogTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hlAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlAuthor As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lblDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkRss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRss As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''lnkRssIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkRssIcon As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''litSocialSharing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSocialSharing As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litSummary As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litEntry As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lblCopyright control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCopyright As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptCategories As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lnkBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkBlogs As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgBlogParentSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBlogParentSeparator As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lnkParentBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkParentBlog As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''imgParentChildSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgParentChildSeparator As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lnkChildBlog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkChildBlog As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''litCategories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCategories As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rptTags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptTags As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lnkTrackBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkTrackBack As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''cmdPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdPrint As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkEditEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkEditEntry As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''pnlComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlComments As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lnkDeleteAllUnapproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDeleteAllUnapproved As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btDeleteAllUnapproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btDeleteAllUnapproved As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lstComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstComments As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''pnlLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlLogin As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmdLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLogin As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddComment As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''valSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''valCommentAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCommentAuthor As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valCommentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valCommentTitle As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valComment As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAuthor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuthor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlGravatar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGravatar As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''imgGravatarPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGravatarPreview As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlWebsite As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtWebsite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWebsite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCommentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCommentTitle As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCommentTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCommentTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCaptcha As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ctlCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlCaptcha As Global.DotNetNuke.UI.WebControls.CaptchaControl

    '''<summary>
    '''cmdAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddComment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cmdDeleteComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdDeleteComment As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''litAddComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litAddComment As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtClientIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientIP As Global.System.Web.UI.WebControls.TextBox
End Class
