'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ViewBlog

 '''<summary>
 '''pnlBlogInfo control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlBlogInfo As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lblAuthorHeader control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAuthorHeader As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblAuthor control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblCreatedHeader control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCreatedHeader As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lblCreated control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblCreated As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lnkRSS control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lnkRSS As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''lblBlogDescription control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lblBlogDescription As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''pnlBlogRss control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents pnlBlogRss As Global.System.Web.UI.WebControls.Panel

 '''<summary>
 '''lnkRecentRss control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lnkRecentRss As Global.System.Web.UI.WebControls.HyperLink

 '''<summary>
 '''InfoEntry control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents InfoEntry As Global.System.Web.UI.WebControls.Label

 '''<summary>
 '''lstBlogView control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lstBlogView As Global.System.Web.UI.WebControls.DataList

 '''<summary>
 '''lstSearchResults control.
 '''</summary>
 '''<remarks>
 '''Auto-generated field.
 '''To modify move field declaration from designer file to code-behind file.
 '''</remarks>
 Protected WithEvents lstSearchResults As Global.System.Web.UI.WebControls.DataList
End Class
