'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

 Partial Public Class Comments

  '''<summary>
  '''pnlComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlComments As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblComments As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lstComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lstComments As Global.System.Web.UI.WebControls.DataList

  '''<summary>
  '''pnlAddComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlAddComment As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''valComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents valComment As Global.System.Web.UI.WebControls.RequiredFieldValidator

  '''<summary>
  '''txtComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtComment As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmdAddComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdAddComment As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''cmdDeleteComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdDeleteComment As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''litAddComment control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents litAddComment As Global.System.Web.UI.WebControls.Literal

  '''<summary>
  '''txtClientIP control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtClientIP As Global.System.Web.UI.WebControls.TextBox
 End Class
End Namespace
