'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

 Partial Public Class ManagementPanel

  '''<summary>
  '''pnlManagement control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlManagement As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''cmdCopyModule control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdCopyModule As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''cmdManageBlogs control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdManageBlogs As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''cmdEditPost control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdEditPost As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''cmdBlog control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdBlog As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''wlwlink control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wlwlink As Global.System.Web.UI.HtmlControls.HtmlAnchor

  '''<summary>
  '''pnlCopyModule control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents pnlCopyModule As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''lblTemplate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTemplate As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddTemplate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddTemplate As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lblShowManagementPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblShowManagementPanel As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowManagementPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowManagementPanel As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lblTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTitle As Global.System.Web.UI.UserControl

  '''<summary>
  '''txtTitle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblPane control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblPane As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddPane control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddPane As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lblInsert control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblInsert As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddPosition control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddPosition As Global.System.Web.UI.WebControls.DropDownList
 End Class
End Namespace
