'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

 Partial Public Class TemplateSettings

  '''<summary>
  '''tblSettings control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents tblSettings As Global.System.Web.UI.WebControls.Table

  '''<summary>
  '''divMessage control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents divMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

  '''<summary>
  '''cmdCancel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

  '''<summary>
  '''cmdUpdate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
 End Class
End Namespace
