'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Controls

 Partial Public Class ViewSettings

  '''<summary>
  '''lblBlogModuleId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblBlogModuleId As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddBlogModuleId control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddBlogModuleId As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lblTemplate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTemplate As Global.System.Web.UI.UserControl

  '''<summary>
  '''ddTemplate control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddTemplate As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''lblShowManagementPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblShowManagementPanel As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowManagementPanel control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowManagementPanel As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lblShowComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblShowComments As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowComments control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowComments As Global.System.Web.UI.WebControls.CheckBox

  '''<summary>
  '''lblShowAllLocales control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblShowAllLocales As Global.System.Web.UI.UserControl

  '''<summary>
  '''chkShowAllLocales control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents chkShowAllLocales As Global.System.Web.UI.WebControls.CheckBox
 End Class
End Namespace
