'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    '''<summary>
    '''blogsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents blogsLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''postsLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents postsLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Blogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Blogs As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dlBlogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlBlogs As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''cmdAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''Posts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Posts As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''grdPosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdPosts As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cmdReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton
End Class
