using DotNetNuke.Common.Utilities;
using DotNetNuke.Entities.Modules;
using DotNetNuke.Entities.Modules.Settings;
using DotNetNuke.Services.Tokens;
using System;

// 
// DNN Connect - http://dnn-connect.org
// Copyright (c) 2015
// by DNN Connect
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated 
// documentation files (the "Software"), to deal in the Software without restriction, including without limitation 
// the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and 
// to permit persons to whom the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or substantial portions 
// of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED 
// TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
// CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
// DEALINGS IN THE SOFTWARE.
// 

using System.Xml;

namespace DotNetNuke.Modules.Blog.Core.Common
{
  [Serializable()]
  public class ModuleSettings : IPropertyAccess
  {
    public string Version { get; set; } = "0.0.0";

    [ModuleSetting]
    public bool AllowWLW { get; set; } = false;

    [ModuleSetting]
    public bool AllowMultipleCategories { get; set; } = true;

    [ModuleSetting]
    public int VocabularyId { get; set; } = -1;

    [ModuleSetting]
    public bool AllowAttachments { get; set; } = true;

    [ModuleSetting]
    public SummaryType SummaryModel { get; set; } = SummaryType.HtmlIndependent;

    [ModuleSetting]
    public string StyleDetectionUrl { get; set; } = "";

    [ModuleSetting]
    public int WLWRecentPostsMax { get; set; } = 10;

    [ModuleSetting]
    public bool AutoGenerateMissingSummary { get; set; } = true;

    [ModuleSetting]
    public int AutoGeneratedSummaryLength { get; set; } = 1000;

    [ModuleSetting]
    public string FacebookAppId { get; set; } = "";

    [ModuleSetting]
    public int FacebookProfileIdProperty { get; set; } = -1;

    [ModuleSetting]
    public bool ModifyPageDetails { get; set; } = false;

    [ModuleSetting]
    public string RssEmail { get; set; } = "";

    [ModuleSetting]
    public int RssDefaultNrItems { get; set; } = 20;

    [ModuleSetting]
    public int RssMaxNrItems { get; set; } = 50;

    [ModuleSetting]
    public int RssTtl { get; set; } = 30;

    [ModuleSetting]
    public int RssImageWidth { get; set; } = 144;

    [ModuleSetting]
    public int RssImageHeight { get; set; } = 96;

    [ModuleSetting]
    public bool RssImageSizeAllowOverride { get; set; } = true;

    [ModuleSetting]
    public bool RssAllowContentInFeed { get; set; } = true;

    [ModuleSetting]
    public string RssDefaultCopyright { get; set; } = "";

    [ModuleSetting]
    public string PortalTemplatesPath { get; set; } = "";

    [ModuleSetting]
    public int IncrementViewCount { get; set; } = 60; // seconds

    [ModuleSetting]
    public bool UseFriendlyURLs { get; set; } = true;

    public string PortalModulePath { get; set; } = "";
    public string PortalModuleMapPath { get; set; } = "";
    public string PortalTemplatesMapPath { get; set; } = "";
    public int ModuleId { get; set; } = -1;

    public static ModuleSettings GetSettings(int moduleId)
    {
      var module = ModuleController.Instance.GetModule(moduleId, -1, true);
      if (module is null)
      {
        throw new ArgumentException($"Module with id {moduleId} not found");
      }
      return GetSettings(module);
    }

    public static ModuleSettings GetSettings(ModuleInfo module)
    {
      var repo = new ModuleSettingsRepository();
      var res = repo.GetSettings(module);

      res.ModuleId = module.ModuleID;

      res.PortalModulePath = DotNetNuke.Entities.Portals.PortalSettings.Current.HomeDirectory;
      if (!res.PortalModulePath.EndsWith("/"))
      {
        res.PortalModulePath += "/";
      }
      res.PortalModulePath += $"Blog/{module.ModuleID}";

      res.PortalModuleMapPath = DotNetNuke.Entities.Portals.PortalSettings.Current.HomeDirectoryMapPath;
      if (!res.PortalModuleMapPath.EndsWith(@"\"))
      {
        res.PortalModuleMapPath += @"\";
      }
      res.PortalModuleMapPath += $"Blog\\{module.ModuleID}";

      res.PortalTemplatesMapPath = $@"{res.PortalModuleMapPath}Templates\";
      if (!System.IO.Directory.Exists(res.PortalTemplatesMapPath))
      {
        System.IO.Directory.CreateDirectory(res.PortalTemplatesMapPath);
      }
      res.PortalTemplatesPath = $"{res.PortalModulePath}Templates/";

      return res;
    }

    public void SaveSettings()
    {
      var module = ModuleController.Instance.GetModule(this.ModuleId, -1, true);
      if (module is null)
      {
        throw new ArgumentException($"Module with id {this.ModuleId} not found");
      }
      var repo = new ModuleSettingsRepository();
      repo.SaveSettings(module, this);
    }

    #region  IPropertyAccess Implementation 
    public string GetProperty(string strPropertyName, string strFormat, System.Globalization.CultureInfo formatProvider, DotNetNuke.Entities.Users.UserInfo AccessingUser, Scope AccessLevel, ref bool PropertyNotFound)
    {
      string OutputFormat = string.Empty;
      var portalSettings = Framework.ServiceLocator<DotNetNuke.Entities.Portals.IPortalController, DotNetNuke.Entities.Portals.PortalController>.Instance.GetCurrentPortalSettings();
      if (string.IsNullOrEmpty(strFormat))
      {
        OutputFormat = "D";
      }
      else
      {
        OutputFormat = strFormat;
      }
      switch (strPropertyName.ToLower() ?? "")
      {
        case "email":
          {
            return PropertyAccess.FormatString(RssEmail, strFormat);
          }
        case "allowmultiplecategories":
          {
            return AllowMultipleCategories.ToString(formatProvider);
          }
        case "allowattachments":
          {
            return AllowAttachments.ToString(formatProvider);
          }
        case "summarymodel":
          {
            return ((int)SummaryModel).ToString();
          }

        case "portaltemplatespath":
          {
            return PropertyAccess.FormatString(PortalTemplatesPath, strFormat);
          }
        case "portalmodulepath":
          {
            return PropertyAccess.FormatString(PortalModulePath, strFormat);
          }
        case "apppath":
          {
            return DotNetNuke.Common.Globals.ApplicationPath;
          }
        case "imagehandlerpath":
          {
            return DotNetNuke.Common.Globals.ResolveUrl(Globals.glbImageHandlerPath);
          }
        case "facebookappid":
          {
            return FacebookAppId;
          }

        default:
          {
            PropertyNotFound = true;
            break;
          }
      }

      return Null.NullString;
    }

    public CacheLevel Cacheability
    {
      get
      {
        return CacheLevel.fullyCacheable;
      }
    }
    #endregion

    #region  Serialization 
    public void Serialize(XmlWriter writer)
    {
      writer.WriteStartElement("Settings");
      writer.WriteElementString("AllowWLW", AllowWLW.ToString());
      writer.WriteElementString("AllowMultipleCategories", AllowMultipleCategories.ToString());
      writer.WriteElementString("VocabularyId", VocabularyId.ToString());
      writer.WriteElementString("AllowAttachments", AllowAttachments.ToString());
      writer.WriteElementString("SummaryModel", SummaryModel.ToString());
      writer.WriteElementString("StyleDetectionUrl", StyleDetectionUrl);
      writer.WriteElementString("WLWRecentPostsMax", WLWRecentPostsMax.ToString());
      writer.WriteElementString("ModifyPageDetails", ModifyPageDetails.ToString());
      writer.WriteElementString("AutoGenerateMissingSummary", AutoGenerateMissingSummary.ToString());
      writer.WriteElementString("AutoGeneratedSummaryLength", AutoGeneratedSummaryLength.ToString());
      writer.WriteElementString("FacebookAppId", FacebookAppId);
      writer.WriteElementString("FacebookProfileIdProperty", FacebookProfileIdProperty.ToString());

      writer.WriteElementString("RssEmail", RssEmail);
      writer.WriteElementString("RssDefaultNrItems", RssDefaultNrItems.ToString());
      writer.WriteElementString("RssMaxNrItems", RssMaxNrItems.ToString());
      writer.WriteElementString("RssTtl", RssTtl.ToString());
      writer.WriteElementString("RssImageWidth", RssImageWidth.ToString());
      writer.WriteElementString("RssImageHeight", RssImageHeight.ToString());
      writer.WriteElementString("RssImageSizeAllowOverride", RssImageSizeAllowOverride.ToString());
      writer.WriteElementString("RssAllowContentInFeed", RssAllowContentInFeed.ToString());
      writer.WriteElementString("RssDefaultCopyright", RssDefaultCopyright);
      writer.WriteElementString("IncrementViewCount", IncrementViewCount.ToString());
      writer.WriteEndElement(); // settings
    }

    public void FromXml(XmlNode xml)
    {
      if (xml is null)
        return;
      AllowWLW = xml.ReadValue("AllowWLW", AllowWLW);
      AllowMultipleCategories = xml.ReadValue("AllowMultipleCategories", AllowMultipleCategories);
      VocabularyId = xml.ReadValue("VocabularyId", VocabularyId);
      AllowAttachments = xml.ReadValue("AllowAttachments", AllowAttachments);
      SummaryModel = xml.ReadValue("SummaryModel", SummaryModel);
      StyleDetectionUrl = xml.ReadValue("StyleDetectionUrl", StyleDetectionUrl);
      WLWRecentPostsMax = xml.ReadValue("WLWRecentPostsMax", WLWRecentPostsMax);
      ModifyPageDetails = xml.ReadValue("ModifyPageDetails", ModifyPageDetails);
      AutoGenerateMissingSummary = xml.ReadValue("AutoGenerateMissingSummary", AutoGenerateMissingSummary);
      AutoGeneratedSummaryLength = xml.ReadValue("AutoGeneratedSummaryLength", AutoGeneratedSummaryLength);
      FacebookAppId = xml.ReadValue("FacebookAppId", FacebookAppId);
      FacebookProfileIdProperty = xml.ReadValue("FacebookProfileIdProperty", FacebookProfileIdProperty);
      RssEmail = xml.ReadValue("RssEmail", RssEmail);
      RssDefaultNrItems = xml.ReadValue("RssDefaultNrItems", RssDefaultNrItems);
      RssMaxNrItems = xml.ReadValue("RssMaxNrItems", RssMaxNrItems);
      RssTtl = xml.ReadValue("RssTtl", RssTtl);
      RssImageWidth = xml.ReadValue("RssImageWidth", RssImageWidth);
      RssImageHeight = xml.ReadValue("RssImageHeight", RssImageHeight);
      RssImageSizeAllowOverride = xml.ReadValue("RssImageSizeAllowOverride", RssImageSizeAllowOverride);
      RssAllowContentInFeed = xml.ReadValue("RssAllowContentInFeed", RssAllowContentInFeed);
      RssDefaultCopyright = xml.ReadValue("RssDefaultCopyright", RssDefaultCopyright);
      IncrementViewCount = xml.ReadValue("IncrementViewCount", IncrementViewCount);
    }
    #endregion

  }

  public class ModuleSettingsRepository : SettingsRepository<ModuleSettings>
  {
  }
}